### ISSUE TITLE
[documentation] The current main branch is no longer compatible with the documentation

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pympipool#163]
The documentation needs to be update and it would be great to add practical examples for the different use cases.

**Comment by mgt16-LANL** [comment]
Hi @jan-janssen - I'll second this one - I was looking over the newer version of pympipool and couldn't find where something similar to Pool is now located.

**Comment by jan-janssen** [comment]
Hi @mgt16-LANL, I agree the documentation has to be added. To answer your question, there is no more `Pool` class, the recommended way is now to use the `Executor` in combination with the `map()` function, which behaves very closely to the `map()` function of the `Pool` class.

**Comment by mgt16-LANL** [comment]
Thanks @jan-janssen! Do you mean importing from the specific type of parallel backend you want - like:
`from pympipool.mpi import PyMPIExecutor`  for mpi backend or `from pympipool.flux import PyFluxExecutor` for flux?

**Comment by jan-janssen** [comment]
Yes, as both backends have different levels of functionality like GPU and OpenMP support which is only available with Flux, it is recommended to explicitly import the interface you want.

**Comment by liamhuber** [comment]
I'm also running into this. Currently the [docs](https://github.com/pyiron/pympipool/blob/a3ed247b98ed81fde7f9cdaa738999111a1decb7/docs/source/interfaces.md?plain=1#L101) are just flat out wrong, namely you can't do the starting point like `from pympipool import Executor` since v0.7.0. 

For me personally this isn't the end of the world, as I'm sufficiently motivated to use the package and can just dig around the code base until I find what I'm looking for, but in general I strongly recommend updating the docs in the same PR as interface changes are made (perhaps with stacked PRs if you are concerned about keeping individual PR sizes compact).

**Comment by jan-janssen** [comment]
@mgt16-LANL and @liamhuber the draft for the new documentation is available online at https://pympipool.readthedocs.io/en/documentation/index.html
