### ISSUE TITLE
[bug] tests on Mac OS time out

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pympipool#191]
Locally they seem to work fine.

**Comment by jan-janssen** [comment]
It is strange that the version of the Mac OS containers was downgraded: 
```
12.7
21G816
```
vs.
```
 macOS
 12.6.9
 21G726
```

**Comment by jan-janssen** [comment]
A similar issue was already reported in https://github.com/actions/runner-images/issues/8642

**Comment by jan-janssen** [comment]
Currently effected pull requests:
* https://github.com/pyiron/pympipool/pull/181
* https://github.com/pyiron/pympipool/pull/190
* https://github.com/pyiron/pympipool/pull/193

**Comment by liamhuber** [comment]
As discussed in the meeting today, OSX tests run fine on bare metal for two of the versions in #240, including failures. The conclusion from this is that the problem is likely MPI+the CI runners, and not pympipool+OSX.

The long-term solution is still to hope that the generic issue @jan-janssen linked above gets resolved.

In the meantime, OSX11 is working extremely consistently, so a stop-gap solution is to use that instead of macos-laters. I plan to go over to pyiron/actions and make the OS versions a workflow variable. In the meantime I also downgraded macos in #241. 

IMO this should still be left open as long as `macos-latest` fails.

**Comment by jan-janssen** [comment]
Fixed in https://github.com/pyiron/pympipool/pull/258
